version: '3.8'

services:
  web:
    extends:
      file: ./docker/common-services.yml
      service: web
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    extends:
        file: ./docker/common-services.yml
        service: db
    env_file:
      - ./.env
  nginx:
    extends:
      file: ./docker/common-services.yml
      service: nginx
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
